apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: reinvent2022 
  region: us-east-2 
  version: "1.24"

vpc:
  cidr: 172.31.0.0/16

nodeGroups:
  - name: eks-node-group
    instanceType: m4.large
    minsize: 1
    maxsize: 3
    desiredCapacity: 2
    privateNetworking: true
