apiVersion: v1
kind: Pod
metadata:
  name: inventoryapi
  labels:
    app: inventoryapi
spec:
  containers:
  - name: inventoryapi
    image: 809312159477.dkr.ecr.us-east-2.amazonaws.com/reinvent2022:inventoryapi
    env:
    - name: REDIS_HOST
      value: "clustercfg.reinvent2022.hxhyby.memorydb.us-east-2.amazonaws.com"
    - name: REDIS_PORT
      value: "6379"
    - name: BACKEND_HOST
      value: "http://10.100.73.107:8000"
    - name: FRONTEND_HOST
      value: "http://10.100.73.107:3000"
